module.exports = {
  JWT_SECRET: 'asdasdasd4as5d4as8d7a8sd4as65d4a8sd7asd4as56d4',
  ACCESS_TOKEN_TIME: 60 * 60 * 6000,
  SALT_ROUNDS: 5,
  SQUADHELP_BANK_NUMBER: '4564654564564564',
  SQUADHELP_BANK_NAME: 'SquadHelp',
  SQUADHELP_BANK_CVC: '453',
  SQUADHELP_BANK_EXPIRY: '11/20',
  CUSTOMER: 'customer',
  CREATOR: 'creator',
  MODERATOR: 'moderator',
  CREATOR_ENTRIES: 'creator_entries',
  CONTEST_STATUS_ACTIVE: 'active',
  CONTEST_STATUS_FINISHED: 'finished',
  CONTEST_STATUS_PENDING: 'pending',
  CONTESTS_DEFAULT_DIR: 'public/contestFiles/',
  NAME_CONTEST: 'name',
  LOGO_CONTEST: 'logo',
  TAGLINE_CONTEST: 'tagline',
  OFFER_COMMAND_REJECT: 'reject',
  OFFER_COMMAND_RESOLVE: 'resolve',
  OFFER_COMMAND_APPROVE: 'approve',
  OFFER_COMMAND_BAN: 'ban',
  OFFER_STATUS_PENDING: 'pending',
  OFFER_STATUS_REJECTED: 'rejected',
  OFFER_STATUS_BANNED: 'banned',
  OFFER_STATUS_WON: 'won',
  OFFER_STATUS_MODERATING: 'moderating',
  FILES_PATH: 'public/',
  SOCKET_CONNECTION: 'connection',
  SOCKET_SUBSCRIBE: 'subscribe',
  SOCKET_UNSUBSCRIBE: 'unsubscribe',
  NOTIFICATION_ENTRY_CREATED: 'onEntryCreated',
  NOTIFICATION_CHANGE_MARK: 'changeMark',
  NOTIFICATION_CHANGE_OFFER_STATUS: 'changeOfferStatus',
  NOTIFICATION_TIMER:'NOTIFICATION_TIMER',
  NEW_MESSAGE: 'newMessage',
  CHANGE_BLOCK_STATUS: 'CHANGE_BLOCK_STATUS',

  DUMPS_PATH: '/server_logs/',
  LOG_PROPS: ['code', 'message', 'stack'],
  LOG_FILE_PATH: '/server_logs/liveNodeLog.json',
  LAST_CHARS_TO_DELETE: 1,
  DAY_LENGTH: 86400000,

  BASE_URL: 'http://localhost:5000/',
  PASSWORD_RESTORE_ROUTE: 'restorePassword',
};
